name: 'Release MBox Plugin'
description: 'Release MBox Plugin by GitHub Actions'
author: 'RyanLeeLY'
inputs:
  token:
    required: true
    description: 'GitHub Token'
  build-path:
    required: false
    description: 'Plugin build path'
  ref:
    required: true
    description: "Branch ref. It must be the same with the workspace repo's current branch"
    default: ${{github.ref}}
  force:
    required: true
    description: 'Override the previous release if exists'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
