name: 'Release MBox Plugin'
description: 'Release MBox Plugin by GitHub Actions'
author: 'RyanLeeLY'
inputs:
  token:
    required: true
    description: 'GitHub Token'
  force:
    required: true
    description: 'Override the previous release if exists'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
